services:
  start-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: start-page
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./scripts:/scripts:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
