services:
  start-page:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: start-page
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./scripts:/scripts:ro
      - /mnt/c/Scripts:/mnt/c/Scripts
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
